functions_csv = "data/functions.csv"
build_target = "Kinopio-S"

[decomp_me]
compiler_name = "clang-4.0.1"
default_compile_flags = "-x c++ -std=gnu++14 -fno-common -fno-strict-aliasing -fno-short-enums -fdata-sections -fPIC -mcpu=cortex-a57+fp+simd+crypto+crc -O3 -fno-slp-vectorize -fno-exceptions -fomit-frame-pointer -Wall -c"
